// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pwa_trabalho_sga.Models;

#nullable disable

namespace pwa_trabalho_sga.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231027162406_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pwa_trabalho_sga.Models.Estudante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Curso")
                        .HasColumnType("text");

                    b.Property<string>("Exames")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int?>("NrEstudante")
                        .HasColumnType("integer");

                    b.Property<string>("Turma")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("estudante");
                });
#pragma warning restore 612, 618
        }
    }
}
